### ISSUE TITLE
save breedR model and reml log in temporary dir for recovery

### ISSUE THREAD

**Issue by famuvie** [famuvie/breedR#100]
Currently, if something goes wrong during the REML fit and the process breaks, the breedR model objects (mf, effects, progsf90) are lost. In order to debug, I need to recreate these objects manually, step by step.

Worse, if them model fit goes ok, but an error is raised when parsing the results, it is impossible to fix and recover the results since the REML log is lost.

- [x] save the breedR model in the temporary directory
- [x] save the REML log in the temporary directory

**Comment by Shi-12345** [comment]
hi,
l am student from China,l have a problem that l cannot solve:
Binary dependencies missing.
Would you like to install them?	

1: Yes
2: No
No matter how I press one, it doesn't show up.

**Comment by famuvie** [comment]
Dear Shi,
Do you have write privileges on your R-package library?
Can you please display the output of:
```r
breedR.getOption('breedR.bin')
system.file('bin', package = 'breedR')
list.files(.Last.value)
```
