### ISSUE TITLE
BreedR won't install

### ISSUE THREAD

**Issue by draperry** [famuvie/breedR#115]
Hi there, 

I have tried multiple times using many different approaches to install breedR but it fails everytime. Example when trying wtih type="source" below. 

> install.packages("breedR", type="source")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/annt/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'https://famuvie.github.io/breedR/src/contrib/breedR_0.12-5.tar.gz'
Content type 'application/gzip' length 4922621 bytes (4.7 MB)
downloaded 4.7 MB

* installing *source* package 'breedR' ...
** using staged installation
** libs
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'breedR'
* removing 'C:/Users/annt/AppData/Local/R/win-library/4.2/breedR'
Warning in install.packages :
  installation of package ‘breedR’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\annt\AppData\Local\Temp\RtmpWM2XFB\downloaded_packages’

**Comment by famuvie** [comment]
Hi,
have you tried installing Rtools as the error message requests?

Best
ƒacu.-
