### ISSUE TITLE
Include some 'generic' model 

### ISSUE THREAD

**Issue by famuvie** [famuvie/breedR#23]
where a user can specify a custom incidence and covariance matrix

**Comment by omikunleseun** [comment]
Hello,
Please how could i analysis for sca, gca and reciprocal effect for linextester mating design.

**Comment by famuvie** [comment]
Hi,
take a look at the [General and Specific Combining Abilities](/famuvie/breedR/wiki/General-and-Specific-Combining-Abilities) tutorial.
