### ISSUE TITLE
Pedigrees with unobserved descendants in `add_animal` models

### ISSUE THREAD

**Issue by stebif68** [famuvie/breedR#55]
Facundo,

There is something about how breedR handles pedigree which is not clear to me. I have 1149 animals and their complete pedigree is made of 18905 animals . If I use this pedigree, I got the following error:

Error in genetic(pedigree, incidence, covariance = relationship.matrix) : 
  The incidence matrix should have as many columns as individuals in the pedigree.

If I use ONLY sire and dam for the 1149, it works fine but it means losing pedigree relationship. 

Stefano

**Comment by famuvie** [comment]
Dear Stefano,

breedR builds internally the full pedigree for the observed individuals, assuming their parents are unrelated.
If you have more information about precedent generations (is this your case?) you can provide your own pedigree as you did, without problem.
Can you provide some reproducible example I can use to determine where is the issue?
Thanks.

**Comment by stebif68** [comment]
Dear Facundo,
Thanks so much for our reply. You are right, I have information from precedent generation and that's the reason why I have a large pedigree. I use REMLF90 and for me it would be extremely useful to use it directly from R. I can send you the example I'm using but I haven't the permission to attach text file. Could you give me your email?
Stefano

BY THE WAY: you are doing a fantastic job!!!

**Comment by famuvie** [comment]
[jersey.franpena.txt](https://github.com/famuvie/breedR/files/29536/jersey.franpena.txt)

**Comment by famuvie** [comment]
I see. It's a situation that I am not sure to have tested specifically.
There might well be a bug. But shouldn't be hard to solve.
You can send the file and the failing code to facundo dot munoz at orleans dot inra dot fr.
Thanks for your help.

**Comment by stebif68** [comment]
Facundo,
I've just sent you an email from ste dot bif68 at gmail dot com.
Best
Stefano

**Comment by famuvie** [comment]
Thanks Stefano.
Bug confirmed.

**Comment by famuvie** [comment]
This issue occurs because you have unobserved individuals in your pedigree which are **descendants** from observed individuals (i.e. present in your dataset).
When the individuals are recoded, these descendants are assigned codes greater than any other observed code.
However, the incidence matrix was (wrongly) built based on the observed codes.
