### ISSUE TITLE
Can't build from repo: img sources for building vignettes not included

### ISSUE THREAD

**Issue by timflutre** [famuvie/breedR#56]
Hello,
here is what I did:

    $ git clone git@github.com:famuvie/breedR.git
    $ R CMD build breedR
    ...
    pandoc: Could not find image `img/gpl-v3-logo.png', skipping...
    pandoc: Could not find image `img/pedigree-background.png', skipping...
    pandoc: Could not find image `img/spatial-background.png', skipping...
    pandoc: Could not find image `img/competition_model.png', skipping...
    ! Package pdftex.def Error: File `img/gpl-v3-logo.png' not found.
    
    See the pdftex.def package documentation for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                  
    l.235 \includegraphics{img/gpl-v3-logo.png}
    
    pandoc: Error producing PDF from TeX source
    Erreur : le traitement de la vignette 'Overview.Rmd' a échoué avec le diagnostic :
    pandoc document conversion failed with error 43
    Exécution arrêtée

It's not urgent as I can install it instead via `devtools::install_github('famuvie/breedR')` instead, but I wanted to let you know.

**Comment by famuvie** [comment]
Thanks for reporting, I'll check.
As a workaround, you can build using
`R CMD build --no-build-vignettes breedR`

However, note you don't get breedR's dependencies installed with this procedure.
Furthermore, if you only want to install, you don't need to clone the whole repository.
It is easiest with `devtools`, or alternatively you can also [install manually](https://github.com/famuvie/breedR/wiki/FAQ#manual-install) all the dependencies.

**Comment by timflutre** [comment]
thanks; indeed I installed via `devtools`
