### ISSUE TITLE
could add a term for genomic relationship inverse matrix?

### ISSUE THREAD

**Issue by yzhlinscau** [famuvie/breedR#97]
Since breedR can deal with pedigree data, then it is possible to run genomic relationship inverse matrix, just like ASReml-R. But in present, I do not have any idea how to pass the genomic relationship inverse matrix into breedR model? So is it possible add a term for genomic relationship inverse matrix? Then, we can run GBLUP with breedR package.

**Comment by famuvie** [comment]
Dear Yuanzhen,
yes it is possible to perform GBLUP with breedR. You can leverage the [`generic` term](https://github.com/famuvie/breedR/wiki/Overview#generic-component) for that.
You can pass any incidence and (inverse) covariance matrices you want, which allows you to use a G-matrix, in particular.

You can see the slides and examples on GBLUP from the site of the [breedR workshop in Poland (2015)](http://famuvie.github.io/breedR/workshop_IBL/). See the material for session 5 on genomic selection.

Hope it helps.
  ƒacu.-
